version: "0.0.1"
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superadmin
    ports:
      - "3306:3306"

  api:
    depends_on: ["db"]
    build:
      context: .
      dockerfile: ./BuildYourHead.Api/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  ui:
    depends_on: ["api"]
    build: ./build-your-head-ui/
    ports:
      - "3000:3000"
    environment: # this doesn't work
      - REACT_APP_API_URL=http://localhost:8080/api