version: "0.0.1"
services:

  db:
    image: mysql:8.0.32
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superadmin
    ports:
      - "3306:3306"

  api:
    depends_on: ["db"]
    build:
      context: .
      dockerfile: ./BuildYourHead.Api/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=server=${DB_HOST};port=${DB_PORT};database=BuildYourHead;user=root;password=superadmin;
      - ImageStorage__ConnectionString=server==${DB_HOST};port=${DB_PORT};database=BuildYourHead.Images;user=root;password=superadmin;

  ui:
    depends_on: ["api"]
    build: ./build-your-head-ui/
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${API_URL}